version: '2'
services:
    pages-app:
        image: pages
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pages-postgresql:5432/pages
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pages-postgresql:
        extends:
            file: postgresql.yml
            service: pages-postgresql
